### PR TITLE
Adding option to allow multiple component ready events

### PR DESCRIPTION
**Pull request by bwittenberg**
When recording an action, consumers may want to record component ready events, even if they have already been recorded in the client metrics session. By adding the ```allowMultipleComponentReady``` option to ```recordAction```, subsequent calls to ```recordComponentReady``` will send events an event each time ```recordComponentReady``` is called.

### CODE REVIEW

**Comment by pbomb** [comment]
I think we can make this simpler. What would happen if we entirely got rid of the concept of "a component only records one component ready"? I'm not sure I see any fallout from doing that.

**Comment by bwittenberg** [comment]
That sounds fine to me, I didn't understand the rationale for only recording a single component ready, so I kept it in there. I'll see if I can find why it was added in the commit history.

**Comment by pbomb** [comment]
It was added ages ago because it's harder in Ext to know when things are really done loading, but if there's still work being done, then it should be fine to record component ready after that additional work is finished. There were probably also some concerns with not all actions being instrumented and blowing out traces, but I don't think that's really an issue as even in this case the traces would be blown out with additional load spans.

**Comment by bwittenberg** [comment]
Ok, great, I'll remove the ```seenThisComponentAlready``` code.

**Pull request closed without merging**
